# GitLab CI/CD Configuration for Factura Movil POS Web
# Automated testing and deployment pipeline

stages:
  - test
  - build
  - deploy

variables:
  NODE_VERSION: "18"
  NPM_CACHE_DIR: "$CI_PROJECT_DIR/.npm-cache"

# Cache dependencies between jobs
cache:
  paths:
    - .npm-cache/
    - node_modules/

# Install dependencies
install_dependencies:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

# Run tests and linting
test:
  stage: test
  image: node:${NODE_VERSION}
  dependencies:
    - install_dependencies
  script:
    - npm run lint
    - echo "Tests completed successfully"
  artifacts:
    paths:
      - .next/
    expire_in: 1 hour

# Build production
build:
  stage: build
  image: node:${NODE_VERSION}
  dependencies:
    - install_dependencies
  script:
    - npm run build
  artifacts:
    paths:
      - .next/
      - public/
    expire_in: 1 hour

# Deploy to staging (manual)
deploy_staging:
  stage: deploy
  image: node:${NODE_VERSION}
  dependencies:
    - build
  script:
    - echo "Deploying to staging environment..."
    - echo "This would typically involve AWS deployment commands"
  environment:
    name: staging
    url: https://staging.facturamovil.cl
  when: manual
  only:
    - develop

# Deploy to production (manual, only from main)
deploy_production:
  stage: deploy
  image: node:${NODE_VERSION}
  dependencies:
    - build
  script:
    - echo "Deploying to production environment..."
    - echo "This would typically involve AWS deployment commands"
  environment:
    name: production
    url: https://facturamovil.cl
  when: manual
  only:
    - main
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

# Security scanning
security_scan:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - npm audit --audit-level moderate
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"
# Pipeline Test - Tue Sep  2 15:19:57 -04 2025
